language: cpp

compiler: gcc

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: BONZOMATIC_X64=ON
    - os: osx
      env: BONZOMATIC_X64=OFF
  exclude:
    - compiler: gcc    # travis bug: https://github.com/travis-ci/travis-ci/issues/4681

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update && brew install sdl2;
    fi
  # travis bug: https://github.com/travis-ci/travis-ci/issues/6048
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 3B4FE6ACC0B21F32 40976EAF437D05B5;
      sudo apt-get update;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots &&
      sudo apt-get update -qq &&
      sudo apt-get install -q -y libsdl2-dev;
    fi

script:
  - cmake -DBONZOMATIC_64BIT=$BONZOMATIC_X64 . && cmake --build .
  
notifications:
  email: false  